import headerImage from "../images/bg-desktop-dark.jpg";

export const darkTheme = {
  body: {
    backgroundColor: "hsl(235, 21%, 11%)",
    height: "100vh",
    position: "relative",
  },
  header: {
    height: "30%",
    backgroundColor: "#fff",
    backgroundImage: `url(${headerImage})`,
  },
  content: {
    position: "absolute",
    top: "25%",
    left: "30%",
    zIndex: 1000,
    backgroundColor: "#25273c",
    width: "40%",
    height: "48%",
    marginLeft: "auto",
    marginRight: "auto",
    transparency: 1,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    maxHeight: "50%",
    overflow: "auto",
    scrollbarWidth: "none",
  },
  listItem: {
    display: "flex",
    flexDirection: "row",
    borderBottom: "0.1px solid #36384d",
    alignItems: "center",
    color: "hsl(234, 39%, 85%)",
    height: 60,
    //cursor: "pointer",
  },
  checked: {
    borderRadius: "50%",
    width: 20,
    height: 20,
    marginRight: 20,
    backgroundImage: "linear-gradient(hsl(192, 100%, 67%), hsl(280, 87%, 65%))",
    marginLeft: 30,
    border: "1px solid #cecece",
    position: "relative",
    cursor: "pointer",
  },
  checkedImg: {
    position: "absolute",
    top: "25%",
    left: "25%",
  },
  unChecked: {
    borderRadius: "50%",
    width: 20,
    height: 20,
    marginRight: 20,
    backgroundColor: "#25273c",
    marginLeft: 30,
    border: "1px solid hsl(233, 14%, 35%)",
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  inner: {
    borderRadius: "50%",
    background: "#25273c",
    height: "80%",
    width: "80%",
    position: "relative",
  },

  listFooter: {
    backgroundColor: "#25273c",
    height: 50,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    paddingLeft: 20,
    paddingRight: 20,
    color: "hsl(233, 14%, 35%)",
    position: "absolute",
    top: "73%",
    left: "30%",
    width: "37.2%",
    zIndex: 1000,
  },
  dragDrop: {
    color: "#484965",
    // backgroundColor: "red",
    height: "65vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  inputField: {
    position: "absolute",
    top: "15%",
    left: "30%",
    zIndex: 1000,
    backgroundColor: "#25273c",
    width: "40%",
    height: "60px",
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: 5,
    display: "flex",
    displayDirection: "row",
    alignItems: "center",
  },

  textInput: {
    width: "90%",
    height: "90%",
    backgroundColor: "transparent",
    border: "none",
    color: "#808080",
    fontFamily: "Josefin Sans",
    fontSize: 18,
    marginRight: 20,
  },
  toggleHeader: {
    position: "absolute",
    top: "5%",
    left: "30%",
    zIndex: 1000,
    backgroundColor: null,
    width: "40%",
    height: "40px",
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: 5,
    color: "white",
  },
};
