import headerImage from "../images/bg-desktop-light.jpg";

export const lightTheme = {
  body: {
    backgroundColor: "hsl(0, 0%, 98%)",
    height: "100vh",
    position: "relative",
  },
  header: {
    height: "30%",
    backgroundColor: "#fff",
    backgroundImage: `url(${headerImage})`,
  },
  content: {
    position: "absolute",
    top: "25%",
    left: "30%",
    zIndex: 1000,
    backgroundColor: "#fff",
    width: "40%",
    height: "48%",
    marginLeft: "auto",
    marginRight: "auto",
    transparency: 1,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    maxHeight: "50%",
    overflow: "auto",
    boxShadow: "43px 110px 37px -44px #cecece",
  },
  listItem: {
    display: "flex",
    displayDirection: "row",
    borderBottom: "0.1px solid hsl(236, 33%, 92%)",
    alignItems: "center",
    color: "hsl(235, 19%, 35%)",
    height: 60,
    //cursor: "pointer",
  },
  checked: {
    borderRadius: "50%",
    width: 20,
    height: 20,
    marginRight: 20,
    backgroundImage: "linear-gradient(hsl(192, 100%, 67%), hsl(280, 87%, 65%))",
    marginLeft: 30,
    border: "1px solid #f1f1fa",
    position: "relative",
    cursor: "pointer",
  },
  checkedImg: {
    position: "absolute",
    top: "25%",
    left: "25%",
  },
  unChecked: {
    borderRadius: "50%",
    width: 20,
    height: 20,
    marginRight: 20,
    backgroundColor: "#fff",
    marginLeft: 30,
    border: "1px solid hsl(233, 11%, 84%)",
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  inner: {
    borderRadius: "50%",
    background: "#fff",
    height: "80%",
    width: "80%",
    position: "relative",
  },
  listFooter: {
    backgroundColor: "#fff",
    height: 50,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    paddingLeft: 20,
    paddingRight: 20,
    color: "hsl(236, 9%, 61%)",
    position: "absolute",
    top: "73%",
    left: "30%",
    width: "37.2%",
    zIndex: 1000,
  },
  dragDrop: {
    color: "#cecece",
    // backgroundColor: "red",
    height: "65vh",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  inputFieldLight: {
    position: "absolute",
    top: "15%",
    left: "30%",
    zIndex: 1000,
    backgroundColor: "#fff",
    width: "40%",
    height: "60px",
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: 5,
    display: "flex",
    displayDirection: "row",
    alignItems: "center",
  },
  textInputLight: {
    width: "90%",
    height: "90%",
    backgroundColor: "transparent",
    border: "none",
    color: "#808080",
    fontFamily: "Josefin Sans",
    fontSize: 18,
    marginRight: 20,
  },
  unCheckedLight: {
    borderRadius: "50%",
    width: 20,
    height: 20,
    marginRight: 20,
    backgroundColor: "#fff",
    marginLeft: 30,
    border: "1px solid #f1f1f1",
    textAlign: "center",
  },
  toggleHeader: {
    position: "absolute",
    top: "5%",
    left: "30%",
    zIndex: 1000,
    backgroundColor: null,
    width: "40%",
    height: "40px",
    marginLeft: "auto",
    marginRight: "auto",
    borderRadius: 5,
    color: "white",
  },
};
